import {
  CreateDateColumn,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from 'typeorm';

/** Timestamps every table has; maintained by TypeORM. */
export abstract class Timestamps {
  @CreateDateColumn({ type: 'timestamptz' })
  createdAt: Date;

  @UpdateDateColumn({ type: 'timestamptz' })
  updatedAt: Date;
}

/**
 * Base of every table with a surrogate key: a uuid generated by the database
 * (gen_random_uuid) plus the timestamps. Link tables with a composite primary
 * key extend `Timestamps` directly.
 */
export abstract class BaseEntity extends Timestamps {
  @PrimaryGeneratedColumn('uuid')
  id: string;
}
